---
- name: Check if tmux is installed
  stat:
    path: /bin/tmux
  register: stat_tmux

- name: Install tmux
  become: true
  package:
    name: tmux
    state: present
  when: stat_tmux.stat.exists==false

- name: Download tmux config
  become: false
  get_url:
    url: https://pastebin.com/raw/Vy5jaWGg
    dest: ~/.tmux.conf
  when: stat_tmux.stat.exists==false
        
- name: Install git, curl, wget, perl
  become: true
  package:
    name: 
      - git
      - curl
      - wget
      - perl
    state: present

- name: Check if ack is installed
  stat: 
    path: /bin/ack
  register: stat_ack

- name: Download ack
  become: true
  get_url:
    url: https://beyondgrep.com/ack-v3.4.0
    dest: /bin/ack
    mode: 0755
  when: stat_ack.stat.exists==false
        
